### ISSUE TITLE
Problem with alerts

### ISSUE THREAD

**Issue by Wruczek** [SoapyHamHocks/MetroSteamSettings#11]
There is problem with alerts.

Metro for Steam:
![http://i.imgur.com/L5vuOkh.png](http://i.imgur.com/L5vuOkh.png)

**Comment by Natanji** [comment]
I think you are running an old version of Metro, at least I had this exact problem and it went away when installing 4.0.4.

**Comment by Wruczek** [comment]
I`ve installed new version. Will wait for this popup to come out. If everything is fine, I will close that issue.

**Comment by Wruczek** [comment]
It seems fine now. Thanks!
