### ISSUE TITLE
Install menu has improper placement of install location selection

### ISSUE THREAD

**Issue by erindal** [SoapyHamHocks/MetroSteamSettings#14]
http://imgur.com/Se6JMXW

It's not a huge issue, but just something to note. The selector still works.

**Comment by goliafrs** [comment]
InstallSubChooseApps_SingleApp.res
line 164
`place { control="InstallFolderCombo" x=24 y=192 margin-right=24 width=max }`
replace on
`place { control="InstallFolderCombo" x=24 y=250 margin-right=24 width=max }`
correct y position
