### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by phillip-haydon** [SoapyHamHocks/MetroSteamSettings#2]
http://boneyardbrew.deviantart.com/art/Metro-for-Steam-3-1-1-292419787

Says V 3.1.1

Download it, and it says 2.0.0.

Doesn't work. Run the install and I get:

![image](https://f.cloud.github.com/assets/895629/1140478/e46ac040-1c9f-11e3-9e0b-ac03bbafbcc0.png)

Restart stream. No new skin available.

**Comment by SoapyHamHocks** [comment]
The .exe should be placed in the same folder as the Skin is installed. Most likely _Skins\Metro for Steam - 3.1.1_.

The error messages could use a bit of work.

**Comment by phillip-haydon** [comment]
Tried changing the directory name to `Metro for Steam - 3.1.1` 

But still doesn't work. :(

**Comment by qmanjr5** [comment]
Place the .exe in whatever folder you installed the skin in ("Metro for Steam" or "Metro for Steam - 3.1.1" or "Metro for Steam - 3.3") and it should work. 

(I realize this is old, but I also was confused by this. Perhaps add a short readme to clarify?)

**Comment by SoapyHamHocks** [comment]
As of 2.2.0 this should no longer be an issue.

Fixed.
